version: '3.3'
services:

  db:
    image: mysql:8.2.0
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - ./.env

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn library.wsgi:application --bind 0:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_files/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  mysql:

