version: '3.3'
services:

  db:
    image: mysql:8.2.0
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    env_file:
      - ./.env


  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: /app/entrypoints/server-entrypoint.sh
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env


  celery:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: /app/entrypoints/worker-entrypoint.sh
    volumes:
      - static_value:/app/static_files/
    depends_on:
      - backend
      - redis
    env_file:
      - ./.env


  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_files/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  mysql:

